### PR TITLE
Fixing converting Boolean, TimeStamp, Date and Byte to .NET native data types

### PR DESCRIPTION
**Pull request by opejanovic**
Just as the title says - Fixing converting OracleBoolean, OracleTimeStamp, OracleDate and OracleBinary to .NET native data types.
Working with Dapper.Oracle i realized that we are missing conversion from Oracle types to .NET native

### CODE REVIEW

**Comment by opejanovic** [comment]
@epaulsen heads up again :)
Today I realized that we are missing more type conversions. We should be fine now.
Sorry for missing this in previous PR.
Would it be a problem to create nuget 2.0.2?

**Comment by epaulsen** [comment]
Sorry, missed this.  Will review shortly.

**Comment by opejanovic** [comment]
@epaulsen any news?

**Comment by epaulsen** [comment]
Looks good, sorry for the delay.  Approved and merged.
A new version should be release within a few days.

**Comment by epaulsen** [comment]
v 2.0.2 pushed to nuget.  Sorry about the delay.

**Pull request merged**
